# numpy

In [1]:
import numpy as np

v1 = np.array([1,2,3,4])
print(v1)

[1 2 3 4]


In [8]:
age = np.array([18,20,43,14,52,12])
print(age >= 18)
print((age < 18) | (age > 35))

[ True  True  True False  True False]
[False False  True  True  True  True]


In [10]:
#фильтрация

filtered = age[(age < 40)]
filtered

array([18, 20, 14, 12])

In [18]:
#многоменый массив

table = np.array([[2, 5, 6], [8, 10, 4]])
print(table)
print(table.shape)   # размеры
print(table.ndim)    # размерность
print(table[1, 1])
print(table[1][1])
print(table[:, 1])   # второй столбец
print(table[0, :])   # первая строка

[[ 2  5  6]
 [ 8 10  4]]
(2, 3)
2
10
10
[ 5 10]
[2 5 6]


# pandas

In [3]:
import pandas as pd

df = pd.DataFrame()
df['STATS'] = [ 9, 10, 7]
df['PROG'] = [ 8, 5, 10]
df    # = display(df)


STATS  PROG
0      9     8
1     10     5
2      7    10

In [4]:
df['PROG']

0     8
1     5
2    10
Name: PROG, dtype: int64

In [5]:
df['PROG'].name

'PROG'

In [6]:
df['PROG'].dtype

dtype('int64')

In [7]:
df['PROG'].values

array([ 8,  5, 10], dtype=int64)

In [8]:
df['AVERAGE'] = (df['PROG'] + df['STATS']) / 2

In [9]:
df

STATS  PROG  AVERAGE
0      9     8      8.5
1     10     5      7.5
2      7    10      8.5

In [11]:
df[['STATS','AVERAGE']]

STATS  AVERAGE
0      9      8.5
1     10      7.5
2      7      8.5

In [12]:
df.columns

Index(['STATS', 'PROG', 'AVERAGE'], dtype='object')

In [13]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [17]:
df.iloc[0]    # строка № 0 - обращение по индексам

STATS      9.0
PROG       8.0
AVERAGE    8.5
Name: 0, dtype: float64

In [22]:
df.index = ['Alice', 'Mark', 'Pete']   # придать имена строкам

In [21]:
df

STATS  PROG  AVERAGE
Alice      9     8      8.5
Mark      10     5      7.5
Pete       7    10      8.5

In [24]:
df.loc['Pete']

STATS       7.0
PROG       10.0
AVERAGE     8.5
Name: Pete, dtype: float64

In [25]:
df.loc['Pete', 'STATS']

7

In [28]:
# словарь в датафрейм

d = {'a': [3,4,5], 'b': [3,5,3]}
df = pd.DataFrame(d)
df

a  b
0  3  3
1  4  5
2  5  3